# Generated by Django 4.2.24 on 2025-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='background_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
