# Generated by Django 5.2.6 on 2025-10-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_alter_add_biblioteca_unique_together_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='rawg_id',
            field=models.IntegerField(blank=True, help_text='ID do jogo na API RAWG', null=True, unique=True),
        ),
    ]
