# Generated by Django 5.2.6 on 2025-11-03 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_jogo_rawg_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaGamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_jogadas', models.PositiveIntegerField(default=0, verbose_name='Horas Jogadas')),
                ('trofeus_totais', models.PositiveIntegerField(default=0, verbose_name='Total de Troféus')),
                ('trofeus_conquistados', models.PositiveIntegerField(default=0, verbose_name='Troféus Conquistados')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='jogos.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'jogo')},
            },
        ),
    ]
