# Generated by Django 5.2.6 on 2025-11-11 11:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_jornadagamer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliar',
            options={'ordering': ['-data_da_avaliacao']},
        ),
        migrations.AddField(
            model_name='avaliar',
            name='data_da_avaliacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='avaliar',
            unique_together={('usuario', 'Jogo')},
        ),
    ]
