# Generated by Django 5.2.6 on 2025-11-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_alter_avaliar_options_avaliar_data_da_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, help_text='Caminho para o avatar predefinido', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jogo_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_favoritos', to='jogos.jogo'),
        ),
    ]
